version: '3'

services:
  app:
    build: .
    command: bash
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=root
      - DATABASE_PASSWORD=12345678
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



